name: GitHub Pages

on:
  push:
    branches:
      - gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run -- test --no-watch --no-progress --browsers=ChromeHeadless

      - name: Prepare and deploy to Github pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ng -- deploy --base-href=3d-print-quoting-website --name=cheesemcbaguette --email="29225021+cheesemcbaguette@users.noreply.github.com"
