name: GitHub Pages

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Prepare and deploy to Github pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ng -- deploy --dir=dist/3d-print-quoting-website --base-href=/3d-print-quoting-website/ --repo="https://github.com/cheesemcbaguette/3d-print-quoting-website.git" --name cheesemcbaguette --email "29225021+cheesemcbaguette@users.noreply.github.com"
